version: 2

sources:
  - name: despesas_queimados
    description: "Dados brutos de despesas do município de Queimados - RJ"
    database: monitorpublico
    schema: despesas_queimados
    tables:
      - name: raw_despesas_pagas
        description: "Dados brutos de despesas pagas - API Queimados"
